# Config
DATABASE_PATH = 'database.sqlite'

# Virtual environment variables
COMMUNITY_TOKEN_VAR = 'COMMUNITY_TOKEN'
APPLICATION_TOKEN_VAR = 'APPLICATION_TOKEN'

REQUIRED_ENV_VARS = [
    'APPLICATION_TOKEN',
    'COMMUNITY_TOKEN',
]
